# This isn't signed, must be run with powershell.exe -ExecutionPolicy bypass ...
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install -y git kubernetes-cli azure-cli vscode visualstudio2017community